# Generated by Django 4.2.5 on 2023-09-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
    ]
